# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploration.Shapes'),
        ),
    ]
