# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0002_shapes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='size',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
