# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0004_unitrelations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitrelations',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
