# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0005_auto_20180211_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='size',
            new_name='size_x',
        ),
        migrations.AddField(
            model_name='parts',
            name='size_y',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='size_z',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
