# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0007_binaryrelations'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='axe_x',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='axe_y',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='axe_z',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
